name: Create server on AWS
run-name: Create Server on AWS



on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  create_server:
    runs-on: ubuntu-latest
    steps:
    - name: Triger Job Template no AAP
      uses: bilalahmad99/github-action-trigger-awx@1.1.0
      with:
        ansible_tower_user: ${{ secrets.ansibleUser }}
        ansible_tower_pass: ${{ secrets.ansiblePass }}
        ansible_tower_url: ${{ secrets.ansibleUrl }}
        job_template_id: "17"
        extra_vars: |
          {
          
          }
